### ISSUE TITLE
hardware: Bluetooth devices get diconnected suddenly

### ISSUE THREAD

**Issue by AhmadMasry** [linuxmint/-mint20.2-beta#13]
The Bluetooth peripherals suddenly disconnect after starting up the laptop.
This happens every time I reboot the laptop, which is HP zbook firefly 15 G7. The Bluetooth keyboard and mouse (Logitech MX keys and MX Master 3) connect to the laptop after startup, but after about a minute or 2 both of them disconnects temporary and reconnects.
I usually notice that this happens after the driver manager starts, but I do not know if they are related.
This is exiting in the beta with all the updates installed and actually also exists in 20.1, but posting it here may bring attention.

**Comment by clefebvre** [comment]
Hi @AhmadMasry 

The driver manager doesn't start automatically... so it shouldn't interfere with this. To make sure you can start it when BT is connected and see if anything happens:

`sudo mintdrivers`

When you lose BT connectivity check your kernel messages:

```
dmesg
journalctl
```

Or use the Logs application to go through system logs.

**Comment by AhmadMasry** [comment]
Thank you at @clefebvre 
The following is the output of journalctl

> Jun 21 17:13:37 ahmad-mint systemd[1091]: Reached target Bluetooth.
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:37 ahmad-mint kernel: input: MX Master 3 Keyboard as /devices/virtual/misc/uhid/0005:046D:B023.0002/input/input30
Jun 21 17:13:37 ahmad-mint kernel: input: MX Master 3 Mouse as /devices/virtual/misc/uhid/0005:046D:B023.0002/input/input31
Jun 21 17:13:37 ahmad-mint kernel: hid-generic 0005:046D:B023.0002: input,hidraw1: BLUETOOTH HID v0.15 Keyboard [MX Master 3] on a4:b1:c1:a0:5f:77
Jun 21 17:13:38 ahmad-mint acpid[731]: input device has been disconnected, fd 20
Jun 21 17:13:38 ahmad-mint kernel: logitech-hidpp-device 0005:046D:B023.0002: HID++ 4.5 device connected.
Jun 21 17:13:38 ahmad-mint kernel: input: Logitech Wireless Mouse MX Master 3 as /devices/virtual/misc/uhid/0005:046D:B023.0002/input/input33
Jun 21 17:13:38 ahmad-mint kernel: logitech-hidpp-device 0005:046D:B023.0002: input,hidraw1: BLUETOOTH HID v0.15 Keyboard [Logitech Wireless Mouse MX Master 3] on a4:b1:c1:a0:5f:77
Jun 21 17:13:38 ahmad-mint upowerd[1023]: treating change event as add on /sys/devices/virtual/misc/uhid/0005:046D:B023.0002/power_supply/hidpp_battery_0
Jun 21 17:13:38 ahmad-mint systemd-logind[768]: Watching system buttons on /dev/input/event21 (Logitech Wireless Mouse MX Master 3)
Jun 21 17:13:41 ahmad-mint dbus-daemon[1125]: [session uid=1000 pid=1125] Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal-server.service' requested by ':1.160>
Jun 21 17:13:41 ahmad-mint systemd[1091]: Created slice apps.slice.
Jun 21 17:13:41 ahmad-mint systemd[1091]: Created slice apps-org.gnome.Terminal.slice.
Jun 21 17:13:41 ahmad-mint systemd[1091]: Starting GNOME Terminal Server...
Jun 21 17:13:41 ahmad-mint dbus-daemon[1125]: [session uid=1000 pid=1125] Successfully activated service 'org.gnome.Terminal'
Jun 21 17:13:41 ahmad-mint systemd[1091]: Started GNOME Terminal Server.
Jun 21 17:13:41 ahmad-mint systemd[1091]: Started VTE child process 2604 launched by gnome-terminal-server process 2597.
Jun 21 17:13:41 ahmad-mint polkitd(authority=local)[759]: Registered Authentication Agent for unix-process:2724:3441 (system bus name :1.84 [flatpak list], object path /org/freedesktop/Poli>
Jun 21 17:13:41 ahmad-mint polkitd(authority=local)[759]: Unregistered Authentication Agent for unix-process:2724:3441 (system bus name :1.84, object path /org/freedesktop/PolicyKit1/Authen>
Jun 21 17:13:44 ahmad-mint systemd[1]: systemd-hostnamed.service: Succeeded.
Jun 21 17:13:45 ahmad-mint systemd-timesyncd[669]: Initial synchronization to time server 91.189.89.199:123 (ntp.ubuntu.com).
Jun 21 17:13:46 ahmad-mint systemd[1]: systemd-fsckd.service: Succeeded.
Jun 21 17:13:47 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:13:47 ahmad-mint kernel: input: MX Keys Keyboard as /devices/virtual/misc/uhid/0005:046D:B35B.0003/input/input34
Jun 21 17:13:47 ahmad-mint kernel: input: MX Keys Mouse as /devices/virtual/misc/uhid/0005:046D:B35B.0003/input/input35
Jun 21 17:13:47 ahmad-mint kernel: input: MX Keys Consumer Control as /devices/virtual/misc/uhid/0005:046D:B35B.0003/input/input36
Jun 21 17:13:47 ahmad-mint kernel: hid-generic 0005:046D:B35B.0003: input,hidraw2: BLUETOOTH HID v0.13 Keyboard [MX Keys] on a4:b1:c1:a0:5f:77
Jun 21 17:13:47 ahmad-mint systemd-logind[768]: Watching system buttons on /dev/input/event22 (MX Keys Keyboard)
Jun 21 17:13:47 ahmad-mint systemd-logind[768]: Watching system buttons on /dev/input/event24 (MX Keys Consumer Control)
Jun 21 17:13:49 ahmad-mint tracker-store[1279]: OK
Jun 21 17:13:49 ahmad-mint systemd[1091]: tracker-store.service: Succeeded.
Jun 21 17:14:08 ahmad-mint acpid[731]: input device has been disconnected, fd 20
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint bluetoothd[734]: bt_uhid_send: Invalid argument (22)
Jun 21 17:14:11 ahmad-mint kernel: logitech-hidpp-device 0005:046D:B023.0004: HID++ 4.5 device connected.
Jun 21 17:14:11 ahmad-mint upowerd[1023]: treating change event as add on /sys/devices/virtual/misc/uhid/0005:046D:B023.0004/power_supply/hidpp_battery_1
Jun 21 17:14:11 ahmad-mint kernel: input: Logitech Wireless Mouse MX Master 3 as /devices/virtual/misc/uhid/0005:046D:B023.0004/input/input38
Jun 21 17:14:11 ahmad-mint kernel: logitech-hidpp-device 0005:046D:B023.0004: input,hidraw1: BLUETOOTH HID v0.15 Keyboard [Logitech Wireless Mouse MX Master 3] on a4:b1:c1:a0:5f:77
Jun 21 17:14:11 ahmad-mint systemd-logind[768]: Watching system buttons on /dev/input/event21 (Logitech Wireless Mouse MX Master 3)
Jun 21 17:14:15 ahmad-mint acpid[731]: input device has been disconnected, fd 21
Jun 21 17:14:15 ahmad-mint acpid[731]: input device has been disconnected, fd 22
Jun 21 17:14:19 ahmad-mint kernel: input: MX Keys Keyboard as /devices/virtual/misc/uhid/0005:046D:B35B.0005/input/input39
Jun 21 17:14:19 ahmad-mint kernel: input: MX Keys Mouse as /devices/virtual/misc/uhid/0005:046D:B35B.0005/input/input40
Jun 21 17:14:19 ahmad-mint kernel: input: MX Keys Consumer Control as /devices/virtual/misc/uhid/0005:046D:B35B.0005/input/input41
Jun 21 17:14:19 ahmad-mint kernel: hid-generic 0005:046D:B35B.0005: input,hidraw2: BLUETOOTH HID v0.13 Keyboard [MX Keys] on a4:b1:c1:a0:5f:77
Jun 21 17:14:19 ahmad-mint systemd-logind[768]: Watching system buttons on /dev/input/event22 (MX Keys Keyboard)
Jun 21 17:14:20 ahmad-mint systemd-logind[768]: Watching system buttons on /dev/input/event24 (MX Keys Consumer Control)

And attached is dmesg
[dmesg.txt](https://github.com/linuxmint/mint20.2-beta/files/6687427/dmesg.txt)

**Comment by clefebvre** [comment]
Hi @AhmadMasry,

This is definitely not related to the driver manager. It looks like it's down to the BT stack. Have a look at https://askubuntu.com/questions/972872/bluetooth-mouse-keeps-disconnecting.

Try the suggestion to install blueman and use its manager to Trust the device.

A few other suggestions are available at https://askubuntu.com/questions/1235456/issues-with-bluetooth-mouse-in-ubuntu-20-04.
