### ISSUE TITLE
Boot failure

### ISSUE THREAD

**Issue by AlanTheLinuxGuy** [linuxmint/-mint20.2-beta#14]
Live-USB of Version 20.2-beta appeared to load and run normally although no testing was performed.  The OS was installed over a prior installation of Version 20.1.  The partition then failed to boot giving an ACPI BIOS Error (see attached screenshot, boot_error.jpg).  The system (minus the OS details) is described in the attached file system_info.txt

![boot_error](https://user-images.githubusercontent.com/76230234/122624800-dea16b00-d06f-11eb-8504-21031282cc7c.jpg)

[system_info.txt](https://github.com/linuxmint/mint20.2-beta/files/6679690/system_info.txt)

**Comment by spamegg1** [comment]
The APCI bugs are unrelated. They show up on normal working systems as well. Hardware manufacturers make BIOS not perfectly compliant with Linux kernel's expectations.

What happens if you type `exit` and hit Enter at the `(initramfs)` prompt? There could be a file system error.

**Comment by AlanTheLinuxGuy** [comment]
Problem resolved.  It may have been an intermittent glitch.  I downloaded and installed the ISO file from a different mirror.  This version booted and functioned correctly.
