### ISSUE TITLE
Mint Software Manager : Apps have their own icons, instead of the provided by the current icon pack

### ISSUE THREAD

**Issue by Jocadbz** [linuxmint/-mint20.2-beta#15]
I'm not sure if this is really a problem, but here we go: When we see an app in the app store, it is usually shown not with its own icon, but with the one provided by the icon pack, as we can see here:
![image](https://user-images.githubusercontent.com/83680590/122625654-b0765800-d07c-11eb-8c32-274fc923f1aa.png)
All of the Third-party apps are displayed with the respective icon from our icon theme. But now, their own icon is displayed :  
![image](https://user-images.githubusercontent.com/83680590/122625721-f501f380-d07c-11eb-9218-0577ac66c086.png)

**Steps to reproduce ( in my case)**
- Just open the Software Manager and reload the cache

**Comment by mtwebster** [comment]
Hi,

This was done deliberately: https://github.com/linuxmint/mintcommon/commit/31f24dfc9c8ed340c9646dbb6142ed701c52f359

Mostly it was for the reason given there, but I also think it makes sense for an app to use its own branding in a 'store', but once it's installed it gets integrated with theme icons

**Comment by Jocadbz** [comment]
Oh, ok. Thanks for the quick answer !
