### ISSUE TITLE
cinnamon: Taskbar program display overflow 

### ISSUE THREAD

**Issue by xiaolongdepc** [linuxmint/-mint20.2-beta#17]
![2021-06-19 18-39-41屏幕截图](https://user-images.githubusercontent.com/85984653/122639783-6c439000-d12e-11eb-9017-fbc8b710b41e.png)

**Comment by leigh123linux** [comment]
This isn't new to beta.

https://github.com/linuxmint/cinnamon/issues/10155

**Comment by clefebvre** [comment]
We'll continue to track this and hopefully fix it in 5.2. It won't happen in this BETA.
