### ISSUE TITLE
xfce: Guest additions not running

### ISSUE THREAD

**Issue by andr1972** [linuxmint/-mint20.2-beta#18]
1. Install linuxmint-20.2-xfce-64bit-beta.iso  on VirtualBox virtual machine
2. Install Guest Additions 

This GA are  not run automatic and is problem run it manually

**Comment by spamegg1** [comment]
Guest Additions are working fine for me on the Cinnamon 20.2 Beta. Can you share more info? Did you install updates from the Update Manager? Maybe there was a kernel update that would require reinstalling the Guest Additions (it needs to build kernel modules). 

What version of Virtualbox are you using? How did you install Guest Additions? 

Can you share the output of `sudo systemctl | grep vbox` from the guest?

**Comment by mtwebster** [comment]
This doesn't seem to be a new issue (at least 20.1 had the issue).

Thunar doesn't auto-run media by default, so inserting guest additions opens the drive in thunar automatically but that's it. Double-clicking the linux installer tries to open it in xed.

The autorun.sh script expects one of konsole, gnome-terminal, mate-terminal or xterm to be installed. None of these are by default.

#### to fix:
If we can override the default xfce4 setting `thunar-volman/autorun/enabled` to true, and install xterm by default, then inserting the guest additions cd will show the autorun dialog and allow the user to start the installer automatically.

**Comment by clefebvre** [comment]
Closing as upstream.
