### ISSUE TITLE
Firefox start page should be https instead of http

### ISSUE THREAD

**Issue by vegam57** [linuxmint/-mint20.2-beta#21]
Firefox on Linux Mint 20.2beta
Firefox start page should be https instead of http for pre-set.
In order not to lower the impression of a safe OS.
![2021-06-20_07-11](https://user-images.githubusercontent.com/78515193/122656709-21f6f900-d198-11eb-826a-ca5c62af778a.png)

**Comment by clefebvre** [comment]
Fixed.
