### ISSUE TITLE
hplip: GUI Print Setting / Installable Options / Duplexer Undetected

### ISSUE THREAD

**Issue by gh4wi** [linuxmint/-mint20.2-beta#24]
HPLIP GUI on Mint 20.2 does not detect that the Duplexer is installed on my HP 932c Printer.
This feature worked ok on MInt 19.3 but does NOT work on Mint 20.2.

**Comment by clefebvre** [comment]
Check https://bugs.launchpad.net/hplip to see if it's known upstream.

**Comment by gh4wi** [comment]
If you start HPLIP GUI on Mint 20.2, then click on Setting / Installable Options, one can not Enable the installed duplexer.
This feature works fine on Mint 19.3. Tested on 3 different PC's /w 3 different printers, HP 932C, HP 8100, HP 8620.
What other info do you need ???

**Comment by clefebvre** [comment]
On a fresh 20.2 installation with HPLIP 3.21.2, hplip-gui is added with `apt install hplip-gui` (from the repository).

In `HPLIP Toolbox`, `Device -> Settings` is greyed out.

In the right pane, I can see `Print Settings`. In this tab I can:

- Select `Basic -> Duplex (Print on both sides of the page)`. This shows three options. Single sided, Two sided (long edge or short edge).
- Select `General -> Double Sided Printing`. Same here, three options, Off, Short or Long edge flip.

Neither of these options are greyed out. This was tested with an HP Envy 5540.
