### ISSUE TITLE
translations: update for stable

### ISSUE THREAD

**Issue by vegam57** [linuxmint/-mint20.2-beta#26]
Hi,
About LM20.2Beta
I want you to pull the update-translation from the LP and deliver to 20.2beta.
In the current 20.2 beta, a new translation of mintupdate was missing.
I want to check the reflection of translation on Beta before the production release of LM20.2

**Comment by clefebvre** [comment]
This is always planned but I suppose it won't hurt to get a github issue to track it. I'll close this when it is done.

**Comment by clefebvre** [comment]
@vegam57 it just occurred to me you wouldn't get the opportunity. We'll definitely update the translations before stable but this might happen close to Stable.

I recommend you download the PO files from Launchpad and try them.

```
apt install mint-dev-tools
mint-build -g mintupdate
```

Then in mintupdate/po place the new PO files.

```
cd mintupdate
dpkg-buildpackage
sudo dpkg -i ../mintupdate*.deb
```

**Comment by vegam57** [comment]
Thank you for your guidance.
I will try it.

**Comment by clefebvre** [comment]
@vegam57 mintupdate 5.7.7 is in the repository now with updated translations.

**Comment by vegam57** [comment]
Thank you again.
I have confirmed that it reflects in a good way.
