### ISSUE TITLE
muffin: Tool shown in background when taking screenshot (was foreground before)

### ISSUE THREAD

**Issue by martinseener** [linuxmint/-mint20.2-beta#28]
In 20.2 beta when taking either a full-screen or partial-screen screenshot, the tool itself is put into background instead of foreground like in 20.1 and before. This adds an additional click on the menubar to open it back up.
Taking screenshot itself works though but this is changed behaviour and should stay in foreground again when taking a screenshot.

**Comment by clefebvre** [comment]
I think this is on muffin..

**Comment by Lurux** [comment]
I also observe this on 20.1 with focus stealing prevention on. Could this be the culprit ?

**Comment by martinseener** [comment]
Didn't have this in 20.1 Can you tell me how to dis/enable this stealing prevention?

**Comment by Lurux** [comment]
> Didn't have this in 20.1 Can you tell me how to dis/enable this stealing prevention?

Windows > Behavior > "Prevent windows which require attention from stealing focus"
