### ISSUE TITLE
Item name in Mintupdate "Blacklist"-> "Blocklist"

### ISSUE THREAD

**Issue by vegam57** [linuxmint/-mint20.2-beta#31]
Suggestion
Item name in Mintupdate "Blacklist"-> "Blocklist"
To be an OS that makes a good impression for everyone 
LaunchPad 
No.205
227
228
302

**Comment by clefebvre** [comment]
No politics please.

**Comment by vegam57** [comment]
![2021-06-22_06-37](https://user-images.githubusercontent.com/78515193/122831186-76c77a80-d324-11eb-8996-357eabb990f3.png)
This is not a political issue.
It is a consideration of kindness and a desire to improve the quality of Mint.
I'm sorry that this idea didn't interest you.

**Comment by scorpion44** [comment]
> ![2021-06-22_06-37](https://user-images.githubusercontent.com/78515193/122831186-76c77a80-d324-11eb-8996-357eabb990f3.png)
> This is not a political issue.
> It is a consideration of kindness and a desire to improve the quality of Mint.
> I'm sorry that this idea didn't interest you.

Yes.  It is a political issue.  It is a progressive leftest issue that only CRT idiots, and commies care about.   I have checked your comment history and you however do not appear to be running around trolling with things like this, you are actually doing proper bug reports.  Changing long standing names of items because it upsets some people is a slippery slope.  Keep up the good work

**Comment by vegam57** [comment]
Trends on the kernel side
index : kernel/git/torvalds/linux.git
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb

**Comment by scorpion44** [comment]
> Trends on the kernel side
> index : kernel/git/torvalds/linux.git
> https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb

Linux is being politicized.  You don't have to do it too.

**Comment by vegam57** [comment]
When the stable version of LM20.2 is released, it will be covered by the mass media.
Many articles with new Mintupdate screens will be exposed.
Some people who see it may have this impression.
LM is still indifferent to that topic.

I'm going to be sorry it happens.
