### ISSUE TITLE
Gdebi won't install Chrome

### ISSUE THREAD

**Issue by Mark-Steele-1961** [linuxmint/-mint20.2-beta#32]
Error: Dependency is not satisfiable: libappindicator1

even after installing libappindicator1 with Synaptic.

**Comment by clefebvre** [comment]
I can't reproduce this. Tested in the Xfce ISO:

![image](https://user-images.githubusercontent.com/1138515/122762357-2523df00-d295-11eb-8a58-803a4b9fc56c.png)

**Comment by Mark-Steele-1961** [comment]
Clement, as I'm new to this, what do you suggest I do?  Re-install 20.2 and try again?  Is it possible that it's hardware related?  I've got it on an ancient Core 2 Duo laptop.

I just reinstalled LM and it now works fine. The only difference I can think of is that I rebooted the machine after applying the updates before trying to install it.
________________________________

**Comment by clefebvre** [comment]
I'll give it a try.

**Comment by Mark-Steele-1961** [comment]
I should have mentioned that it's got the Broadcom version of the kernel as well.  But it did work at the second attempt after a rebuild.

________________________________

**Comment by clefebvre** [comment]
It must have been a temporary issue in your APT cache, I can't reproduce it here, even on a fully updated system.

**Comment by Mark-Steele-1961** [comment]
Thanks very much for having a go.

________________________________
