### ISSUE TITLE
Nemo search recursively by default?

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/-mint20.2-beta#33]
Linux Mint 20.2 Cinnamon: 

By default, the Nemo search for files does not search recursively. Doesn't it make sense to enable this option by default? I suspect that most users expect this feature.

**Comment by mtwebster** [comment]
Already done: https://github.com/linuxmint/nemo/commit/71d12d54bfbd9060b69a8bd7c88efddb8343aa4f

**Comment by jakoblm** [comment]
Thanks.

**Comment by jakoblm** [comment]
Thanks. But wasn't the point here to remember the settings of the last search? I was going to suggest that recursive search should be enabled from the very first search.
