### ISSUE TITLE
"Compress..." translation is not used by nemo-extensions

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/-mint20.2-beta#34]
Linux Mint 20.2 Cinnamon: 

A few German translations are missing: 

1) In the context menu (right mouse button) it is still called "Compress". In German it is called "Komprimieren". 

2) In the settings of the update manager -> "Automation" everything is still in English. 

It would be great if this would be translated until the release.

**Comment by xenopeek** [comment]
2nd issue is known and translation team has already completed the translations for that. It will be translated on the final release.

1st issue is I think a new one. I checked in another language and Compress is also not translated there:
![image](https://user-images.githubusercontent.com/21159972/122814472-88813180-d2d4-11eb-9090-11d81f31dc6c.png)

For German I can see Compress... is translated on Launchpad https://translations.launchpad.net/linuxmint/latest/+pots/nemo-extensions/de/61/+translate and the nemo-extensions code looks to want to use that https://github.com/linuxmint/nemo-extensions/blob/master/nemo-fileroller/src/nemo-fileroller.c#L375.
