### ISSUE TITLE
Request: "Send by email" back in context menu?

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/-mint20.2-beta#36]
I have been missing the "Send by email" function in the Nemo context menu for some time. I had already opened a request for this: https://github.com/linuxmint/nemo/issues/2638. I have created a personal "Nemo action" as described there, but would be grateful if this would be set up officially again. Would that still be possible until the release of Mint 20.2?

**Comment by clefebvre** [comment]
No, this was removed on purpose. That said in 20.3 we'll introduce actions as spices, so you'll see many nemo actions become available including this one.
