### ISSUE TITLE
nemo-preview: epub loads indefinitely

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/-mint20.2-beta#4]
```
 * Nemo version 5.0.1
 * Is issue with  windowed nemo?
 * Distribution - (Mint 20.1 - unofficial? beta)
 * Graphics hardware:- NVIDIA GP108 - nouveau
 *  64 bit
 ```

**Issue**

For EPUB file types, attempting a file preview leads to an an infinite wait.
No CPU appears to be used, but a blank widow with an in-progress indication runs forever.

**Steps to reproduce**
Select an EPUB file - I've tried a lot of other file-types, but this appears to be the only problematic one.
Press the space bar.
**wait**

**Expected behaviour**

If the filetype is not catered for, then an enlarged picture of the icon would be a reasonable behaviour.
This appears to be the default for many "impossible" file types.

**Other information**
Perhaps a timeout for previews is needed?

**Comment by clefebvre** [comment]
It looks like we're failing to produce thumbs also for epub files.

**Comment by clefebvre** [comment]
Here's an epub to test: https://contentserver.adobe.com/store/books/GeographyofBliss_oneChapter.epub

**Comment by Jeremy7701** [comment]
I've tried it in a beta version of Mint in a VM - see video.
I pressed the space bar to initiate a preview.
Xreader displays this file, including cover perfectly.


https://user-images.githubusercontent.com/52585119/122558792-64082980-d036-11eb-9508-997d26bcefa5.mp4

**Comment by Jeremy7701** [comment]
I've tried it in a beta version of Mint in a VM - see video.
I pressed the space bar to initiate a preview.
Xreader displays this file, including cover perfectly.
I've fed it through `handbrake` - video problem?

https://user-images.githubusercontent.com/52585119/122559600-720a7a00-d037-11eb-8703-a93b13243ed9.mp4

**Comment by Jeremy7701** [comment]
> It looks like we're failing to produce thumbs also for epub files.

There is a Python 3 epub thumbnailer at [https://github.com/marianosimone/epub-thumbnailer](https://github.com/marianosimone/epub-thumbnailer)

However, given the timescale and complexity, I'd settle for this to be delayed until the next nemo release.

**Comment by mtwebster** [comment]
Unfortunately this isn't fixable at the moment. Nor is thumbnailing, due to how epub documents are rendered. I've disabled the content type so that you'll get the 'fallback' preview instead for these.

**Comment by Jeremy7701** [comment]
Unfortunately there is a lot of variation in different epub files.
I managed a BASH script that produced a cover page most of the time - but it was slow and didn't always work.
