### ISSUE TITLE
Bulky : Inserting text in file-extension is wrong

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/-mint20.2-beta#41]
1. Enter a file eg. doc1.txt
2. Select "insert"
3. Select "extension only"
4. Enter x as a text => file will be renamed as doc1x.txt

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/bulky/commit/3aa17129e6e994511969a1c417272ade805d1ea6
