### ISSUE TITLE
Bulky : Can't change file-extension to first-character uppercase

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/-mint20.2-beta#42]
1. Add file doc1.txt
2. Select "Change case"
3. Select "Extension only"
4. Select "First character uppercase" 
=> extension isn't changed to Txt

**Comment by Jeremy7701** [comment]
Confirmed. But this is not restricted to any particular extension.

However, choosing extension only, "Title case" does change just the first character to upper case.
