### ISSUE TITLE
Bulky : Is Bulky able to rename directories?

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/-mint20.2-beta#43]
The dialog-title states : File Renamer - Rename files and directories

How can one rename a directory ? There is no button to add a directory

**Comment by clefebvre** [comment]
It was tedious to add two buttons for the two file types.. GTK won't let us have a single dialog for this. That said you can use Nemo to select files and folders and right-click rename...

**Comment by MenthaSuaveolens** [comment]
Thank you for the comments. I didn't realize that Bulky gets started when you select multiple directories to rename in Nemo
