### ISSUE TITLE
Update Manager did not pick up updated Cinnamon Spice Applet

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/-mint20.2-beta#44]
I did a fresh install of the beta on 16 June and at the time Weather by Gr3q (weather@mockturtl) was at version 3.0.8.

This morning I noticed it was at:
Weather by Gr3q
UUID: weather@mockturtl
Last edited: 16 hours ago 2021-06-21, 14:55
Last commit: [c8b86f72] weather@mockturtl update 3.0.10 (#3816)

The Update Manager has not notified of any updates available for this Applet.
I did a manual install from the zip file instead of using the Applets manger in System Settings and replace the json config file so I don't have to re-enter all the settings.  Could this have made a difference?

![Screenshot from 2021-06-22 09-00-08](https://user-images.githubusercontent.com/45599505/122928886-48539a80-d338-11eb-936a-b1433ab55357.png)

How does the update manager track updates made in the Cinnamon Spices Applets?

**Comment by mtwebster** [comment]
It looks as though it may be getting skipped here:
https://github.com/linuxmint/Cinnamon/blob/master/python3/cinnamon/harvester.py#L265-L269
This is the code that mintupdate uses.

If the installed metadata doesn't have a 'last_edited' field, it's skipped.

It appears to be the same in cinnamon-settings - I assume it doesn't show updates there either?
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/Spices.py#L466-L469

We could easily have it assume yes instead of no, but I'm not sure what is most appropriate - I'm in favor of leaving it as is - you may have installed some customized version of the applet, and you don't want it wiped out by the updater. @clefebvre ?

**Comment by clefebvre** [comment]
The only way you don't have last_edited is if it's installed manually, and without using the cinnamon CLI right?

**Comment by Acheron17** [comment]
Where would the installed metadata file be that is checked?
Here?: ~/.local/share/cinnamon/applets/weather@mockturtl$ ls
3.0  arrow-icons  icons          po                yahoo-bridge.py
3.8  icon.png     metadata.json  requirements.txt

**Comment by clefebvre** [comment]
Yes I think so.

**Comment by Acheron17** [comment]
Okay, i see now.
        "4.8"
    ],
    "author": "Gr3q",
    "last-edited": 1624305355
}
Needs to be in the metadata.json file for it to be picked up, otherwise its is assumed a custom install.

**Comment by Acheron17** [comment]
You can probably close this issue since it seems to be a corner case created by the way the applet was installed.

**Comment by Acheron17** [comment]
After adding a "last-edited": 1623805200 for (GMT): Wednesday, June 16, 2021 1:00:00 AM, I would have expected it to be picked as an update.  I did this just to see if the Update Manager would pick it up.  This did not happen.

**Comment by clefebvre** [comment]
I'm not sure this is related to mintupdate, can you check with:

`cinnamon-spice-updater --list-json applet`

**Comment by clefebvre** [comment]
I get this here:

```
{
    "weather@mockturtl": {
        "author": "",
        "commit_id": "1c7383fe4ab93637b090b227e87d919bedb2d428",
        "commit_msg": "Turkish translation update 3.0.9 (#3819)",
        "description": "Affiche les pr\u00e9visions m\u00e9t\u00e9orologiques locales",
        "link": "https://cinnamon-spices.linuxmint.com/applets/view/17",
        "name": "M\u00e9t\u00e9o",
        "new_version": "2021.06.22",
        "old_version": "2021.05.13",
        "size": 796195,
        "spice_type": "applet",
        "uuid": "weather@mockturtl"
    }
}
```

(I installed this applet via Cinnamon).

**Comment by Acheron17** [comment]
I removed this applet and reinstalled via the Cinnamon Applet panel then re imported my settings.  When I run that command it comes up with an empty set of brackets.  The assumption is it will be empty until a new version is rolled out?

**Comment by Acheron17** [comment]
I have a clearer understanding how this process works between the ~/.cinnamon/spices.cache/applet/index.json, the python harvester and ~/.local/share/cinnamon/applets/weather@mockturtl/metadata.json.

I am going to close this with the confidence, that if installed correctly, the Cinnamon applets will receive an update.  Thank you.
