### ISSUE TITLE
Notes : Add an option to start Notes automatically in the taskbar

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/-mint20.2-beta#45]
I you want to start Notes each time you log in, one can add Notes to the startup-applications. However after log-in, the notes are shown but the Notes-dialog as well. Is there a way that only the notes itself pop up after login? I'm not always interested in the Notes-dialog itself. I want to view the Notes-dialog, I can right-click on the icon on the panel.

**Comment by collinss** [comment]
Disabling Preferences->General->"Show the main window automatically" should give you what you want. Also, there's an autostart option in preferences so you don't actually need to add it to startup applications.
