### ISSUE TITLE
Nemo:Nemo(5.0.1)does not break into subdirectories and search.

### ISSUE THREAD

**Issue by vegam57** [linuxmint/-mint20.2-beta#47]
Is it an expected specification that Nemo(5.0.1)does not break into subdirectories and search?
Either the file name or the content
Nemo(4.8.6) can search for subdirectories by file name search. 
![2021-06-23_14-32](https://user-images.githubusercontent.com/78515193/123041428-3f45f480-d430-11eb-962d-d9305e180ff8.png)

**Comment by princepaul** [comment]
Did you select this option to "Enable Search Recursively"?

![Screenshot from 2021-06-23 18-11-57](https://user-images.githubusercontent.com/3245122/123098687-08330b80-d44f-11eb-9d66-3497b2517786.png)

**Comment by vegam57** [comment]
No, I didn't click on it.
I think that button should be on by default.
And the pop-up hint should be "Enable Search **subdirectories**".

**Comment by mtwebster** [comment]
The defaults have been changed: https://github.com/linuxmint/nemo/commit/71d12d54bfbd9060b69a8bd7c88efddb8343aa4f

**Comment by vegam57** [comment]
I was relieved by your explanation.
However, I think it's better fate to change the pop-up hint so that home users is not going to get a flat tire on the forum. 
Thank you.
