### ISSUE TITLE
Vertical artefact on presentation-screen using LO-Impress

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/-mint20.2-beta#49]
Please have a look at bug https://github.com/linuxmint/cinnamon/issues/8926

This bug is still present in LM 20.2 and happens only with the Cinnamon-version, not with Mate nor with xfce. It happens with LibreOffice as well as with the Calligra Stage. I never encountered this issue on other linux-distributions.

I tried it again with LM 20.2 on an usb-stick (no installation on the laptop). I just made a LO-impress-presentation and played the presentation on a TV-screen (HDMI-connection)

Please have a look at this
![Screenshot from 2021-06-23 17-57-12](https://user-images.githubusercontent.com/47174957/123148559-a9768d80-d460-11eb-84a8-4073331d8433.png)

**Comment by kelebek333** [comment]
Hi,

Can You try to change Vsync method?

System Settings => General => VSync Method

**Comment by MenthaSuaveolens** [comment]
Hi kelebek333, 
I played around with some of the composition-settings as you suggested and also changed the scale of the presentation 4:3 to 16:9 but the artifact remains. If you exchange screens (see exchange-button on the presentation-console, then artifact shows up on the left side of the laptop-screen. This artifact is annoying especially if make presentations with a beamer on a large screen. The room is always darkened somehow and then the white character of artifact on the right of the canvas draws attention.

 The artifact has always the same width. I enlarged the top of the artifact with GIMP in the image attached
![VerticalArtefact](https://user-images.githubusercontent.com/47174957/123450101-a2748a00-d5dc-11eb-9f91-c0c8d15f22d9.jpg)

**Comment by mtwebster** [comment]
Ok I've figured out what's wrong but I'm not sure we'll include it in the final 20.2 iso - there are chances for regressions that I don't want to introduce this close to release.

I've built some packages if you'd like to try the fix:
https://www.dropbox.com/sh/5ctcfoiez3tejt8/AAC_gylaIlnIT0VgEytGqxmca?dl=0

Download the three packages there and install them from a terminal:
```
sudo dpkg -i *.deb
```

If something goes wrong (cinnamon crashes, etc...) you should be able to run:
```
apt install libmuffin0 muffin-common gir1.2-meta-muffin-0.0
```
And it will restore the current 'release' versions. You can do this from a tty if you can't use the session itself (ctrl-alt-f2) - then restart.

**Comment by MenthaSuaveolens** [comment]
Hi Michael, thank you for issuing a solution. However, I don't see any improvement. For testing, I played around with some different configurations regarding the relative positions of the screens to each other. If  you configure them as stacked displays, then the artifact becomes a horizontal one. In the attachment, I zipped several screenshots. I took a screenshot of the configuration and then a screenshot of the presentation. The interesting one is if the secondary display is on top of the primary screen, then you can notice the top of the menubar in the bottom of the secondary screen.

Installation-log
sudo dpkg -i *.deb
dpkg: warning: downgrading gir1.2-meta-muffin-0.0 from 5.0.1+uma to 5.0.1
(Reading database ... 282091 files and directories currently installed.)
Preparing to unpack gir1.2-meta-muffin-0.0_5.0.1_amd64.deb ...
Unpacking gir1.2-meta-muffin-0.0 (5.0.1) over (5.0.1+uma) ...
dpkg: warning: downgrading libmuffin0 from 5.0.1+uma to 5.0.1
Preparing to unpack libmuffin0_5.0.1_amd64.deb ...
Unpacking libmuffin0 (5.0.1) over (5.0.1+uma) ...
dpkg: warning: downgrading muffin-common from 5.0.1+uma to 5.0.1
Preparing to unpack muffin-common_5.0.1_all.deb ...
Unpacking muffin-common (5.0.1) over (5.0.1+uma) ...
Setting up muffin-common (5.0.1) ...
Processing triggers for libglib2.0-0:amd64 (2.64.6-1~ubuntu20.04.3) ...
Setting up libmuffin0 (5.0.1) ...
Setting up gir1.2-meta-muffin-0.0 (5.0.1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for man-db (2.9.1-1) ...
[ScreenshotsTestingMuffin.zip](https://github.com/linuxmint/mint20.2-beta/files/6739953/ScreenshotsTestingMuffin.zip)

**Comment by mtwebster** [comment]
Hi did you restart cinnamon after installing those packages (alt-F2, r, enter, or log out and back in).

**Comment by MenthaSuaveolens** [comment]
Oh I'm so sorry. Indeed, restarting Cinnamon solves the issue! Thank you for forwarding a solution.

**Comment by clefebvre** [comment]
Quick note on this, we might push it as an update post-release to get time to test it more.
