### ISSUE TITLE
im-launch in the autostart (unwanted wayland-related entry ?)

### ISSUE THREAD

**Issue by Lurux** [linuxmint/-mint20.2-beta#51]
Hi,

I have noticed 20.2 still has an entry called "im-launch" in the cinnamon autostart settings.

It has no description, and seems to be related to Wayland support.

Since Mint doesn't use Wayland, wouldn't it make sense to delete or at least hide this entry from the settings ?

**Comment by xenopeek** [comment]
im-launch launches the input method switcher. On X11 sessions this gets launched through `/etc/X11/Xsession.d/70im-config_launch`, not needing this autostart entry. That doesn't work on Wayland sessions and that's what this autostart entry is for: to launch the input method switcher on Wayland sessions.

Cinnamon currently only runs X11 session so this autostart entry _could_ be blacklisted. Adding it to the autostart-blacklist on https://github.com/linuxmint/cinnamon-session/blob/master/data/org.cinnamon.SessionManager.gschema.xml.  But then make a note to not forget to remove it from the blacklist if Cinnamon can also run Wayland sessions…

Here's the contents of the autostart file
```
[Desktop Entry]
Name=im-launch
Exec=sh -c 'if [ "x$XDG_SESSION_TYPE" = "xwayland" ] ; then exec env IM_CONFIG_CHECK_ENV=1 im-launch true; fi'
TryExec=im-launch
Type=Application
```
I think perhaps it should be upstreamed to https://salsa.debian.org/input-method-team to request to use a more descriptive Name in this file and to add a Comment describing what it is for?

**Comment by Lurux** [comment]
A lot of entries in /etc/xdg/autostart have `NoDisplay=true`, why not this one ?

Also yeah a more descriptive name and description would be welcome. Same goes for `xapp-sn-watcher` (even though it actually has a description, the name is a bit weird)

**Comment by clefebvre** [comment]
Closing as it's upstream.

**Comment by Lurux** [comment]
I understand.

Sorry for the noise, I didn't know it was an upstream thing.
