### ISSUE TITLE
Clearly disclose the automatic removal of unused flatpak runtimes when enabling auto-updates in the update manager

### ISSUE THREAD

**Issue by Lurux** [linuxmint/-mint20.2-beta#52]
Hi,

Wouldn't it make sense to remove the unused flatpak runtimes as part of automated maintenance, instead of doing it as part of the "automated flatpak updates" routine ?

***

Also, if the automated flatpak updates are going to be disabled by default, does this mean people will have no way to update them through the GUI ? :thinking:

Please tell me if I'm missing something here !

**Comment by Jeremy7701** [comment]
I shall be blacklisting flatpak - or possibly pinning it, just to make sure.

**Comment by clefebvre** [comment]
Flaptak UI update management is coming in 20.3. For now we just have the option to update them all and clean their unused runtimes.

**Comment by Lurux** [comment]
> Flaptak UI update management is coming in 20.3. For now we just have the option to update them all and clean their unused runtimes.

@clefebvre Thank you. Maybe I should have explained myself better, but this was not the main point of my issue.

> Wouldn't it make sense to remove the unused flatpak runtimes as part of automated maintenance, instead of doing it as part of the "automated flatpak updates" routine ?

Granted, that is a small detail, but people might be surprised if the unused runtimes get cleaned up even if they never checked an option to do that.

For example, I might not want to uninstall an unused runtime, in order to avoid re-downloading it next time I install a flatpak that depends on it.

Is there any way to mark a flatpak runtime in order to prevent its removal, like can be done with regular packages ?

Thanks !

**Comment by clefebvre** [comment]
There's no way at the moment no, other than unchecking that option.

**Comment by clefebvre** [comment]
I agree with your point. I don't think it matters all that much though because the use case is very niche.

**Comment by Lurux** [comment]
Ok, I understand. I think this will not be a problem anyway as soon as we have manual flatpak updates in the next release :slightly_smiling_face:
