### ISSUE TITLE
xed: getting a dark theme that shows misspellings legibly

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/-mint20.2-beta#53]
I am not the writer of the comment on this page (the Cinnamon beta release announcement [page](https://blog.linuxmint.com/?p=4077)). Yet, since the author has not opened an issue here, I tried to follow the instructions that Clem gave in response to that author - instructions that included the instruction to open an issue here.

Those instructions, by Clem, read in full as follows.

```
The content of the text document is themed separately from the GTK theme using a GTKSourceView theme. We can ship with one which is readable in dark themes if you can find one you like:

https://wiki.gnome.org/Projects/GtkSourceView/StyleSchemes

Place the themes in ~/.local/share/gtksourceview-4/styles and find one you’re happy with. You should create an issue on github (in the BETA repo linked above) so we can keep track of it.
```

I downloaded the dark 'Monokai extended theme' from [that style page](https://wiki.gnome.org/Projects/GtkSourceView/StyleSchemes). I gave it an XML extension and saved it in the recommend place. To do that save I had to create `/gtksourceview-4` and `styles`. Then I ran xed. xed did not find the theme. I pointed it toward the theme. It rejected it, saying: 'The selected colour scheme cannot be installed. _xed seems to want a different type of file._

**Comment by JosephMcc** [comment]
Make sure you follow all the instructions properly. I just tried with that same theme and it worked fine here.

**Comment by LinuxOnTheDesktop** [comment]
I had much trouble getting xed to recognise the files. But anyway, I managed to try these themes:

- monokai extended
- matrix
- greenscreen

The other dark themes were not easily downloadable.

On none of those themes was the underline that indicates misspelling sufficiently visible.

I note also the following.

xed makes it hard to know when one has enabled a theme.

At least one default theme name cannot be read properly when using a system dark theme. That is bad.

In xed, under seemingly any theme and at least on one of my systems (I tested on only one system and it is a system that is not Hi-DPI), the caret flashes for a while and leaves its foot behind when it has disappeared, i.e. does not flash off completely. Also: for some reason, after a while it ceases flashing entirely. [EDITED to insert a missing word.]

**Comment by clefebvre** [comment]
> On none of those themes was the underline that indicates misspelling sufficiently visible.

This is the main issue here. Spell check is useless in dark GTK themes unless you tell Xed to use a light GtkSourceView theme and that goes against the look people want with dark themes.

I was hoping we'd find a GtkSourceView theme that worked and we'd ship that in Mint, but there doesn't seem to be any. I don't know what is responsible for the color of the red squiggle in Xed...

**Comment by clefebvre** [comment]
I'm gonna need to close this. I don't think it's themeable... I get this issue with any GtkSourceView and any GTK theme really. This should be reported upstream to GNOME directly and fixed for Adwaita, gspell, GTK 3 before we can do anything here.

**Comment by LinuxOnTheDesktop** [comment]
OK. Perhaps the other problems - the two problems with the caret, the difficulty in knowing whether one has selected a theme, and the difficulty in reading at least one theme name - are fixable by Mint. It is important that people find the editor shipped with Mint to be usable.

Also, though I'm sure you don't want to hear this, I wonder about the wisdom of reinventing the wheel. That is: I take it that mature, good editors exist; creating and shipping your own one seems to be asking for problems. True, a reason for shipping your own might be that you can give it good integration with the rest of the system, but that is precisely what is not happening here.

If you like I will move all or some of what I have said to https://github.com/linuxmint/xed.

**Comment by JosephMcc** [comment]
Did a bit of research this morning. The red underline color is hard coded in gspell and there is already an open issue on it's gitlab about it.
