### ISSUE TITLE
Mintupdate - Preferences - Automation

### ISSUE THREAD

**Issue by tomas-52** [linuxmint/-mint20.2-beta#56]
I could not check the behaviour of automatic removal of old kernels and dependencies, where it says that it never removes the manually installed ones, but on 20.1 I have made the experience that when it was turned on it removed a link created to such a kernel (not the kernel itself). Is it OK?

**Comment by clefebvre** [comment]
It's quite complicated, it performs an apt autoclean which removes unused kernels but at Ubuntu packaging level some kernels are preserved for a little while, so it can keep more than a few. The last time we reviewed this feature we did find it a little bit complex and ambiguous but it did work properly.
