### ISSUE TITLE
gnome-maps: doesn't start

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/-mint20.2-beta#57]
https://bugs.launchpad.net/ubuntu/+source/gnome-maps/+bug/1930699

Wait for Ubuntu to fix it.
If nothing happens, we fix it in Mint prior to stable.

**Comment by kelebek333** [comment]
This is working. https://launchpad.net/~juanjo-benages/+archive/ubuntu/fixes

**Comment by clefebvre** [comment]
Fixed. GNOME Maps 3.38.2-1 was backported in 20.2, 20.1 and 20 today.
