### ISSUE TITLE
cinnamon: Added item for unknown purposes

### ISSUE THREAD

**Issue by vegam57** [linuxmint/-mint20.2-beta#58]
Cinnamon 5.0.3
What is this?
![2021-06-26_05-56](https://user-images.githubusercontent.com/78515193/123485108-6d9c1d80-d644-11eb-811c-95a236d9440a.png)

**Comment by clefebvre** [comment]
```
clem@airtop ~ $ apt contains texdoctk
texlive-base: /etc/texmf/texdoctk
texlive-base: /etc/texmf/texdoctk/texdocrc.defaults
ubuntu-settings: /usr/share/ubuntu/applications/texdoctk.desktop
ubuntu-settings: /usr/share/ubuntu-wayland/applications/texdoctk.desktop
clem@airtop ~ $ more /usr/share/ubuntu/applications/texdoctk.desktop
[Desktop Entry]
Name=TeXdoctk
Exec=texdoctk
Type=Application
Terminal=false
Categories=Settings;
NoDisplay=true
X-Ubuntu-Gettext-Domain=ubuntu-default-launchers
```

It comes from ubuntu-settings but it's a NoDisplay=true so I'm not sure why it appears in your menu. Type the following to make sure you didn't override it:

`search in ~/.local/share/applications/ for textdoc`

**Comment by vegam57** [comment]
In my environment
![2021-06-26_07-09](https://user-images.githubusercontent.com/78515193/123489722-91179600-d64d-11eb-9f9e-2fbf70d994b8.png)
I haven't touched it.
![スクリーンショット 2021-06-26 06-53-05](https://user-images.githubusercontent.com/78515193/123489384-cd96c200-d64c-11eb-8f46-1d3eb47d7a3d.png)

**Comment by vegam57** [comment]
I look at the place on Nemo
Empty
![2021-06-26_08-16](https://user-images.githubusercontent.com/78515193/123493402-4733ad80-d657-11eb-9f6e-3f5302f83094.png)

**Comment by mtwebster** [comment]
For me the installed desktop file doesn't have NoDisplay:
/usr/share/applications/texdoctk.desktop:
```
[Desktop Entry]
Name=TeXdoctk
Exec=texdoctk
Type=Application
Terminal=false
Categories=Settings;
```

Btw, you can click the 'Edit desktop file' button in the menu editor to view the actual file being used.

This is installed by texlive-base:
```
mtwebster@p51laptop:~> dpkg -S /usr/share/applications/texdoctk.desktop 
texlive-base: /usr/share/applications/texdoctk.desktop
```

**Comment by mtwebster** [comment]
Unfortunately this gets installed due to nemo depending on texlive-binaries as of 5.0.2, used for formatting latex documents for content search. These are text documents so they could be read by the basic text search but this eliminates any noise from the markup language.

**Comment by vegam57** [comment]
In my environment
/usr/share/applications/texdoctk.desktop
is same.

[Desktop Entry]
Name=TeXdoctk
Exec=texdoctk
Type=Application
Terminal=false
Categories=Settings;

I understand the purpose of adding the item.
If possible, I think it is a good idea to hide it from the menu.
I pray that it is only my environment.
To prevent misunderstandings with adware.

**Comment by Acheron17** [comment]
It also added 120 MB in fonts I didn't ask for or will ever use in any other application like a word processor or spreadsheet.  So now I have to take measures to mitigate this.   Sometimes less is more.  Just offering the search functionality of GREP would have been enough.

**Comment by mtwebster** [comment]
> Just offering the search functionality of GREP would have been enough.

Sorry, I disagree. Latex files are full of markup that would end up as false positives.

Replaced detex with untex, it's only 30kb installed with no additional dependencies.
