### ISSUE TITLE
Some processes run multi intances after relogin

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/-mint20.2-beta#59]
Hi,

The following processes are running multiple instances after relogin. 

applet (system-config-printer-applet)
agent (geoclue agent)
csd-printer

For reproducing logout and relogin. 
Run following command or search with gnome-system-monitor

`pgrep -l 'csd-printer|applet|agent'`

The following output was taken after two relogins.

```
16731 csd-printer
16749 agent
16921 applet.py
17245 csd-printer
17269 agent
17273 applet.py
17576 ssh-agent
17716 csd-printer
17734 agent
17739 applet.py
```

I create a file named system-config-printer-applet on /usr/local/bin/ for workaround applet.py issue. This prevent multi instance for applet.py.

```
#!/bin/sh
if ! pgrep -x "applet.py" > /dev/null
then
    prefix=/usr
    exec ${prefix}/share/system-config-printer/applet.py "$@"
fi
```

Also, I create a file named geoclue-2.0-agent on /usr/local/bin/ and edit /etc/xdg/autostart/geoclue-demo-agent.desktop file for workaround agent issue. This prevent multi instance for agent.

```
#!/bin/sh
if ! pgrep -x "agent" > /dev/null
then
    /bin/bash -c /usr/libexec/geoclue-2.0/demos/agent &
fi
```

However I couldn't solve multiple instances working issue for csd-printer.

**Comment by leigh123linux** [comment]
Edit  /etc/systemd/logind.conf and uncomment and change value to yes

```
#KillUserProcesses=no
```

to

```
KillUserProcesses=yes
```

**Comment by mtwebster** [comment]
I don't have an issue with csd-printer, but I can reproduce the other two.

**Comment by leigh123linux** [comment]
@mtwebster logind should cull the session apps.

**Comment by kelebek333** [comment]
@leigh123linux , thanks,

I create a file /etc/systemd/logind.conf.d/KillUserProcesses.conf containing the following lines.

```
[Login]
KillUserProcesses=yes
```
Then reboot and the issue solved. 

@mtwebster , I changed slick-greeter to lightdm-gtk-greeter. Maybe the csd-printer problem is caused by this. But issue solved by _KillUserProcesses=yes_

**Comment by mtwebster** [comment]
The printer applet and geoclue programs are existing (upstream) issues. I'm not sure whether or not we'll override logind defaults yet, though.

**Comment by clefebvre** [comment]
I remember systemd upstream being asked to default to yes and strongly rejecting the idea. I'd have to dig more to know why though... I don't see myself changing this either, specifically not within the BETA phase.

Let's treat this as upstream and add an item in the roadmap to look at it again.
