### ISSUE TITLE
observation: Iso didn't boot on Ventoy formated USB stick

### ISSUE THREAD

**Issue by enigma131** [linuxmint/-mint20.2-beta#6]
As many testers, I put my Distros under test on a Ventoy prepared USB key.
All earliers isos of Mint was working as is ..
What would be changed in Iso building ? Or what are limitations ?
I have tested with downloads from 2 sites, including the one from http://mirror.csclub.uwaterloo.ca/linuxmint/
I have taken Cinnamon version, I'm on UEFI and at boot i get only cursor (not blinking) at top left corner.
SHA 256 is verified OK

**Comment by clefebvre** [comment]
Nothing is changed since 20.1, same grub, same isolinux, same build process, the kernel is slightly newer but that shouldn't really matter.

**Comment by enigma131** [comment]
Thanks for answer. I've just try the Ventoy prepared stick on a other computer in CSM compatible mode and it works. 
So I will post a bug report to Ventoy's Github ... wait and see:
https://github.com/ventoy/Ventoy/issues/965

**Comment by enigma131** [comment]
Workaround for people who have same problem : 
When you are in Ventoy's main menu, press ctrl+r to enter GRUB2 mode and then select the Mint 20.2 beta ISO and boot.
Problem is not solved , only need this workaround for LM 20.x isos
