### ISSUE TITLE
HW recognition

### ISSUE THREAD

**Issue by tomas-52** [linuxmint/-mint20.2-beta#63]
I have an ATI Radeon video card in my PC, so I was rather surprised to find Support for nVidia Prime (activated) in Startup Applications. Is it a bug or is there some reason for that?

**Comment by enigma131** [comment]
I think support for nVidia prime is always activated (I'm with a intel HD graphics) , I don't know why ? Publicity ?

**Comment by tomas-52** [comment]
I would rather say that  is not publicity, the web is full of questions of how to make nVidia cards work, so I think it is rather done to solve these problems.
But I do not understand why people that do not have these cards should have this software installed and running.
I hope it is safe to stop it and remove, that is why I ask.

**Comment by xenopeek** [comment]
As the description in Startup Applications says, it is just to show a tray icon when a compatible graphics card is detected:

> Shows a tray icon when a compatible NVIDIA Optimus graphics card is detected

You can run it yourself on your system with command `/usr/lib/nvidia-prime-applet/nvidia-prime` and it will respond the following if you don't have the Nvidia packages installed:

> Aborting: Check that the nvidia-settings and nvidia-prime packages are installed.

And if you do install those on your AMD system it would instead respond:

> No NVIDIA card detected!

So it doesn't do anything unless you have a NVIDIA Optimus system and have installed the necessary packages for it. But if you have then it works automatically which is what this is for. So if you add a Nvidia graphics card to your system at some point this tray icon will show up. It's convenience.

You can disable it in Startup Applications if you want. Again, it doesn't do anything unless your system meets the requirements.
