### ISSUE TITLE
mintmenu - wrong sorting of documents (continued and some questions)

### ISSUE THREAD

**Issue by tomas-52** [linuxmint/-mint20.2-beta#64]
First of all, thank you for the update, it works.

As the issue is marked as closed, I suppose I could not write this there, so I started this:

1. I suppose that the update will be ported to previous versions of Mint (just a matter of time)
2. before the update there were just small differences between mint-menu and mate-menu, will the changes be ported also there?
3. the basic differences I have seen were those in setting their preferences and some of them can be set only using dconf
4. the most important of them is the number of recent documents and how they are displayed (the height of their window cannot be changed from the preferences app and changing height for system or places has no effect, in dconf I have set the height to 630 for 20 documents to have them without a scroll-bar, I wonder if that could be adjusted automatically or would collide with other settings)
5. the width can also be set in dconf, but as far as I could see, it has no effect regarding the length of the name of document displayed, if it is long it is just cut off at some place and ... added, if the width is set to a great value, just an empty space is added on both sides of the column of names. Can this be changed?

**Comment by xenopeek** [comment]
I've numbered your bullet points above so I can refer to them.

For 1: I've noted the suggestion.

For 2 & 3: mate-menu is a fork of mint-menu and isn't developed by Linux Mint.

For 4 & 5: those are improvements beyond the scope of 20.2 beta testing. If there is not already a similar issue for this on https://github.com/linuxmint/mintmenu/ you could make feature requests there for setting the number of recent documents and for configuring menu size.
