### ISSUE TITLE
mintinstall does not show flatpak installed by command line as installed applications

### ISSUE THREAD

**Issue by haggen88** [linuxmint/-mint20.2-beta#65]
Because in Software Manager the flatpak only appears as a list [of approximately 200 applications that have reviews] it is common to go to flathub.org to look for applications that are not listed. 

On that site are the "Command line instructions" to install the applications, using that method I noticed that such apps do not appear in mintinstall when checking Installed Applications.

**Comment by mtwebster** [comment]
Mintinstall installs flatpaks system-wide - I'm not sure what instructions you used, but it's possible you installed to the user location instead, which would prevent mintinstall from noticing them.

Mintinstall is able to install from a .flatpakref file (the file that gets downloaded from flathub when you click on the 'install' button).
Just try to open it with the default application (double-click in the file manager, etc..).

**Comment by haggen88** [comment]
I used the instructions that come out on the web, for example for https://flathub.org/apps/details/org.audacityteam.Audacity
It would be to execute in a command line:

flatpak install flathub org.audacityteam.Audacity

the app is installed, it is visible in the main menu of cinnamon but it is not listed in Sotware Manager when executing the option "show installed applications". 

--
In this case Audacity and Blanket were installed by command line in the terminal and on the other hand Melody was installed from Software Manager :
![1](https://user-images.githubusercontent.com/68134588/123551616-93a6e800-d740-11eb-8509-f8cac9c79aa0.png)
