### ISSUE TITLE
XFCE: Panel Transparency Issue

### ISSUE THREAD

**Issue by HopelessHarry** [linuxmint/-mint20.2-beta#66]
This may well be an upstream xfce 4.16 problem.
When Panel transparency is enabled in Panel Preferences / Settings, ghost window buttons of closed applications can be seen through the transparency. This obviously is not noticed when a solid panel colour is used. 
![Screenshot_2021-06-27_20-57-31](https://user-images.githubusercontent.com/52999728/123557716-6b43db80-d78a-11eb-98af-a1f28479e13d.png)
This can be seen at the bottom left of the panel, in the screenshot.

**Comment by xenopeek** [comment]
This is upstream and a bug in Xfce 4.16. There are multiple reports on similar glitches with panel transparency upstream. Like https://forum.xfce.org/viewtopic.php?id=15021 and issues reported this year on https://gitlab.xfce.org/xfce/xfce4-panel/-/issues?scope=all&utf8=%E2%9C%93&state=opened&search=transparency.

I tested on VirtualBox and the solution in https://forum.xfce.org/viewtopic.php?id=13233 mentioned in the first link above works. Though I had to change the setting and log out & back in. The xfwm4 --replace didn't work.

This is what solved transparency glitching on VirtualBox:
```
xfconf-query -c xfwm4 -p /general/vblank_mode -t string -s "xpresent" --create
```
Depending on your graphics card and whether running on real hardware you may need to try one of the other vblank_mode.
