### ISSUE TITLE
Theme: clickable region in the Mint-Y

### ISSUE THREAD

**Issue by vegam57** [linuxmint/-mint20.2-beta#67]
Has this matter previously announced on your blog been incorporated? 

>A small improvement was made in the Mint-Y theme. The titlebar buttons are still the same size but their clickable region will be enlarged in Linux Mint 20.1.
https://blog.linuxmint.com/?p=3969

![スクリーンショット 2021-06-28 06-52-07](https://user-images.githubusercontent.com/78515193/123560486-63f9ed80-d7dd-11eb-8e6a-2f1e197a7789.png)

**Comment by mtwebster** [comment]
Looks like it: https://github.com/linuxmint/mint-themes/commit/a40ce14cb8ac3e23db08cfbdeae7067be383e595

**Comment by JosephMcc** [comment]
This was a very small change and was included in 20.1

**Comment by vegam57** [comment]
I understand.
Regarding this matter,
I am patiently waiting for improvements that I can clearly experience.
Thank you.

**Comment by mtwebster** [comment]
If you are on the 20.2 beta, you should already be experiencing them.
