### ISSUE TITLE
xfce: Unable to access Clock

### ISSUE THREAD

**Issue by xendistar** [linuxmint/-mint20.2-beta#72]
Current setup is just over a week old, I set the timezone ok during setup but now I can not access the clock. I can right click on the clock in the system tray and then select properties and that will bring the clock window up. If I click on the Time and Date Setting button it bring up a smaller window with a closed padlock and a large unlock button next to it. but it does not matter how I click on the button it does not unlock so I am unable to check my location (which is blank) or the ntp server is set to.

If I go into the XFCE start menu and go into System >> Time and date, I get the same Time and Date window as the main image with exactly the same issue

Laptop spec and details

```
mit@NX1:~$ inxi -Fxxxz
System:    Kernel: 5.4.0-77-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.16.0 
           tk: Gtk 3.24.20 info: xfce4-panel wm: xfwm4 dm: LightDM 1.30.0 
           Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: LENOVO product: 24296JG v: ThinkPad T530 serial: <filter> 
           Chassis: type: 10 serial: <filter> 
           Mobo: LENOVO model: 24296JG v: Win8 Pro DPK TPG serial: <filter> 
           UEFI [Legacy]: LENOVO v: G4ETB2WW (2.72 ) date: 04/10/2018 
Battery:   ID-1: BAT0 charge: 49.5 Wh condition: 52.2/93.6 Wh (56%) volts: 12.5/11.1 
           model: LGC 45N1011 type: Li-ion serial: <filter> status: Unknown 
CPU:       Topology: Quad Core model: Intel Core i7-3630QM bits: 64 type: MT MCP 
           arch: Ivy Bridge rev: 9 L2 cache: 6144 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 38313 
           Speed: 1197 MHz min/max: 1200/3400 MHz Core speeds (MHz): 1: 1197 2: 1198 3: 1197 
           4: 1197 5: 1197 6: 1199 7: 1197 8: 1198 
Graphics:  Device-1: Intel 3rd Gen Core processor Graphics vendor: Lenovo driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0166 
           Device-2: NVIDIA GF108M [NVS 5400M] vendor: Lenovo driver: nvidia v: 390.143 
           bus ID: 01:00.0 chip ID: 10de:0def 
           Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1600x900~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: NVS 5400M/PCIe/SSE2 v: 4.6.0 NVIDIA 390.143 direct render: Yes 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Lenovo 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:1e20 
           Device-2: NVIDIA GF108 High Definition Audio vendor: Lenovo driver: snd_hda_intel 
           v: kernel bus ID: 01:00.1 chip ID: 10de:0bea 
           Sound Server: ALSA v: k5.4.0-77-generic 
Network:   Device-1: Intel 82579LM Gigabit Network vendor: Lenovo driver: e1000e v: 3.2.6-k 
           port: 7080 bus ID: 00:19.0 chip ID: 8086:1502 
           IF: enp0s25 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Intel Centrino Advanced-N 6205 [Taylor Peak] driver: iwlwifi v: kernel 
           port: 6000 bus ID: 03:00.0 chip ID: 8086:0085 
           IF: wlp3s0 state: down mac: <filter> 
           Device-3: Ericsson Business Mobile Networks BV H5321 gw Mobile Broadband Driver 
           type: USB driver: cdc_acm,cdc_mbim,cdc_wdm bus ID: 3-4:3 chip ID: 0bdb:1926 
           serial: <filter> 
           IF: wwan0 state: down mac: <filter> 
           IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
Drives:    Local Storage: total: 1.13 TiB used: 408.09 GiB (35.3%) 
           ID-1: /dev/sda vendor: Crucial model: CT240BX500SSD1 size: 223.57 GiB speed: 6.0 Gb/s 
           serial: <filter> rev: R013 scheme: MBR 
           ID-2: /dev/sdb type: USB vendor: Toshiba model: External USB 3.0 size: 931.51 GiB 
           serial: <filter> rev: 5438 scheme: MBR 
Partition: ID-1: / size: 39.10 GiB used: 7.93 GiB (20.3%) fs: ext4 dev: /dev/sda1 
           ID-2: /home size: 170.10 GiB used: 34.42 GiB (20.2%) fs: ext4 dev: /dev/sda2 
           ID-3: swap-1 size: 9.76 GiB used: 512 KiB (0.0%) fs: swap dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 63.0 C mobo: 0.0 C gpu: nvidia temp: 58 C 
           Fan Speeds (RPM): cpu: 2873 
Info:      Processes: 271 Uptime: 3h 55m Memory: 15.33 GiB used: 6.84 GiB (44.6%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Shell: bash v: 5.0.17 
           running in: xfce4-terminal inxi: 3.0.38
```
![broken-clock](https://user-images.githubusercontent.com/38419513/124024104-a9d5d200-d9e6-11eb-930f-6585cf97edf0.jpg)

**Comment by xenopeek** [comment]
Can you try running the command `time-admin` from the terminal. This will open the Time and Date Settings dialog. Maybe it will provide some message on the terminal as to why it is locked and won't unlock.

**Comment by xendistar** [comment]
This is what I get

mit@NX1:~$ time-admin

** (time-admin:2996): WARNING **: 17:10:15.516: Error acquiring permission: Failed to acquire permission for action-id org.freedesktop.systemtoolsbackends.set

Running it as sudo time-admin unlocks the windows and lets me access the settings.

**Comment by xenopeek** [comment]
I can reproduce the `Failed to acquire permission for action-id org.freedesktop.systemtoolsbackends.set` error but only by clicking the Unlock button 3 times in a row and each time typing an incorrect password in the Authenticate dialog. I'm not sure that is what is happening on your end. Does an Authenticate dialog show up for you? Where you are asked to type your password after clicking the Unlock button.

If you're not seeing the Authenticate dialog then maybe, can you check, is PolicyKit Authentication Agent disabled? That's the only thing I could find as mentioned causing the above error. You can check by opening Session and Startup from your menu (it's in Settings category, or just start typing to find it) and on the Application Autostart tab confirm whether PolicyKit Authentication Agent is enabled (has a check mark in front of it).

**Comment by xendistar** [comment]
I checked the Policykit Authentication Agent and found it was disabled, enabled it and now the unlock work as it should, once clicked, asks for password and then unlocks once password is accepted.

I consider the issue resolved, thanks for your help xenopeek
