### ISSUE TITLE
Partition Not Mounted On Startup

### ISSUE THREAD

**Issue by ovari** [linuxmint/-mint20.2-beta#73]
On every startup, the computer does not mount `Partition 3` as shown in the image below.

![PartitionNotMountedOnStartup](https://user-images.githubusercontent.com/17465872/124045266-a24c1280-da52-11eb-8e3d-a4201ee1cbe0.png)

Can `Partition 3` automatically mount as all USB drives are automatically mounted on startup?

Thank you

**Comment by mtwebster** [comment]
That's a partition on an internal drive - unlike usb drives, those aren't mounted at startup by default. You'll need to click the gear icon and 'Edit mount options'. In that popup you can turn off 'user session defaults' and modify the behavior of that particular drive.

**Comment by ovari** [comment]
Thank you it worked
