### ISSUE TITLE
Control center on Mate - default window size

### ISSUE THREAD

**Issue by tomas-52** [linuxmint/-mint20.2-beta#76]
The window size of the control centre was probably chosen when the resolution of displays was low. Unluckily the system does not remember the resized window so it forces he user to resize the window every time he opens the centre so that he may see all of its contents. Could you set new default size of the window? (I think that 4 columns of icons instead of 3 would help much.)
Probably to make the system remember the size of the window would be asking too much, but it is the alternative solution.

**Comment by clefebvre** [comment]
It's a good default size to fit 1024x768. People buying budget netbooks still use very low resolutions, and so do people on budget HiDPI. You can report it upstream to MATE if you want but they're likely to reject it. They might be more open to remembering the size though.
