### ISSUE TITLE
Bulky : Problem with very long filenames

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/-mint20.2-beta#78]
Create a file with a substantial long filename (see screenshot in attachment)

Bulky 1.6

If I want to rename the words "bla" with "blaBLA", then the changed filename is listed up properly into the "new name"-field, but the name doesn't get changed in the filesystem.
![RenamingLongFileNames](https://user-images.githubusercontent.com/47174957/124176140-cd644f80-daae-11eb-9f60-dfa02e143f96.png)

**Comment by mtwebster** [comment]
You can't have filenames longer than 255 bytes (this is a limitation in Linux).

**Comment by mtwebster** [comment]
We'll merge this at some point soon, after the final release.

https://github.com/linuxmint/bulky/pull/6
