### ISSUE TITLE
bulky : Filenames are removed when entering CTRL-C 

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/-mint20.2-beta#79]
Bulky 1.6

1. Add a file
2. Enter Ctrl-C in the "find"-field or "name"-field or "replace"-field
3. Filenames are removed from the application

I encountered this bug when entering a file. I tried to copy part of the filename by using Ctrl-C.

**Comment by clefebvre** [comment]
Fixed in 1.7
