### ISSUE TITLE
Firefox starts but disappears from the panel/screen when in auto start.

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/-mint20.2-beta#80]
I know this is a late report but it took a while to figure out how to duplicate it since Mint and Firefox are changing at the same time.
The issue is, if you start Firefox as an item in "Startup Applications", Firefox will start up along with the other applications you have in "Startup Applications", but it will present itself with a orange highlighted button on the application panel.  Then if you click anywhere on the Firefox window, it disappears.  It is still running but you can't access it.  System is in "Window List" and not "Grouped Window List".  Using the latest release of Firefox (89.0.2+linuxmint1+uma) on a fully updated Beta system.  There is nothing in the logs, xsession errors, etc. to indicate why this is happening. 

To duplicate, add Firefox as a startup item in "Startup Applications" and restart the system.

**Comment by clefebvre** [comment]
I can't reproduce it.

Tested with both modern and traditional layouts (using mintwelcome to switch) and both FF 89.0.1 and 89.0.2.

Firefox appears fullscreen then if I resize it, the next time it starts in the size it had before.

**Comment by Acheron17** [comment]
Looks like its something caused by Firefox.  When google chrome is setup in auto start the issue does not occur.  I'll go ahead and close it since it can't be easily reproduced and there is no information in the logs about why it is happening.
