### ISSUE TITLE
nemo: Searching - case sensitive / recursive search

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/-mint20.2-beta#9]
Searches in nemo. The case-sensitive (or not) and recursive (or not) button setting is not at all clear.

_Suggestion_:- Alter the "hover text" to display the current setting.
Currently, changing the setting doesn't cause a change to the "hover text".
[Provided tool tips are enabled]

But any method of showing the current setting would be good.

**Comment by mtwebster** [comment]
Maybe it's your theme? Mint-X has a bit less contrast between states than I like, personally.

Honestly I think it's pretty clear:
![image](https://user-images.githubusercontent.com/262776/122612271-dab22080-d050-11eb-94ae-e71fc4192f04.png)

It's fairly consistent with other apps:

Xed:
![xed-case](https://user-images.githubusercontent.com/262776/122612649-7c397200-d051-11eb-9493-f58228984108.gif)

Sublime Text:
![sublime-case](https://user-images.githubusercontent.com/262776/122612666-8491ad00-d051-11eb-9edf-b0b8adbbd34a.gif)

edit: One thing we have done is make the default positions for these buttons match the old search behavior (non-case-sensitive, recursion on), it's just not in the current nemo version.

**Comment by Jeremy7701** [comment]
I accept this.
All changes sometimes take time to get used to them.
Since the default is to match the old behaviour, people will get accustomed to the new features.
